nav:
    - Linux-OS-kernel-is-event-driven: Linux-OS-kernel-is-event-driven.md
    - Kernel-control-path-and-reentrant-kernel: Kernel-control-path-and-reentrant-kernel.md
    - Linux-OS-interrupt-and-interrupte-handler: Linux-OS-interrupt-and-interrupte-handler.md
    - Control-path-&-Context-&-Context-switch: Control-path-&-Context-&-Context-switch.md