nav:
    - Introduction: index.md
    - Design-of-gdb: Design-of-gdb
    - Guide-to-controlling-process: Guide-to-controlling-process.md
    - Guide-to-examining-data: Guide-to-examining-data.md
    - Point-in-GDB: Point-in-GDB.md
    - Shared-library: Shared-library.md
    - Function: Function.md
    - Automate: Automate
    - Debug-assembly: Debug-assembly.md
    - gdb-primer: gdb-primer