nav:
    - Introduction: index.md
    - System-V-IPC: System-V-IPC
    - POSIX-semaphores: POSIX-semaphores.md
    - POSIX-message-queues: POSIX-message-queues.md
    - Unix: Unix
    - Tools: Tools