nav:
    - Organization-of-process: Organization-of-process
    - Process-state: Process-state
    - Exit: Exit
    - Daemon: Daemon
    - Proc-filesystem: Proc-filesystem
    - IPC: IPC
    
    
    