nav:
    - 10.11-Convenience-Variables: 10.11-Convenience-Variables.md
    - 10.13-Registers: 10.13-Registers.md
    - 10.19-Produce-a-Core-File-from-Your-Program: 10.19-Produce-a-Core-File-from-Your-Program.md