nav:
    - Introduction: index.md
    ########## 一些杂项、公共问题##########                  
    - Common: Common
    ########## lib描述linux OS的重要的库等##########     
    - Lib: Lib
    ########## 在Linux OS中进行programming的哲学##########       
    - Philosophy: philosophy
    ########## process是这些内容的核心##########
    - Multitasking: Multitasking
    ########## process的一个主要活动就是IO##########
    - IO: IO
    ########## 时间是一个非常重要的话题##########
    - Time: Time

    ########## 信号是一个非常重要的话题##########
    - Signal: Signal
    
    ########## 系统提供的虚拟化功能##########
    - Virtualization: 05-Linux-Virtualization
        
    ########## OS提供的一些基础功能，比如日志等##########
    - Util: 06-Util
      
    ########## 终端也是一个非常重要的内容，我们都是通过pseudo-terminal登录到系统的##########
    - Terminal: Terminal

    ########## 那些经常会碰到的错误##########
    - Computer-errors: Computer-errors
  
    - Kernel-module: Linux-Kernel-module

    
    